version: '3'

services:

  rabbit:
    image: rabbitmq:latest
    expose:
      - '5672'

  replica:
    build:
      context: ..
      dockerfile: integrational_tests/Dockerfile.Replica
    restart: always
    command:
      bash -c "
      sleep 10 &&
      rm -f ./integrational_tests/db/replica_db.sqlite3 &&
      python manage.py makemigrations --settings=integrational_tests.replica_settings &&
      python manage.py makemigrations dj_replica --settings=integrational_tests.replica_settings &&
      python manage.py migrate --settings=integrational_tests.replica_settings &&
      python manage.py start_cqrs_consumer --settings=integrational_tests.replica_settings
      "
    container_name: django_cqrs_test_replica
    depends_on:
      - rabbit
    volumes:
      - ./db:/replica/db
      - ../dj_cqrs:/replica/dj_cqrs

  master:
    build:
      context: ..
      dockerfile: integrational_tests/Dockerfile.Master
    restart: always
    command:
      bash -c "sleep 12 && pytest integrational_tests/"
    container_name: django_cqrs_test_master
    depends_on:
      - rabbit
      - replica
    volumes:
      - ./db:/master/db
      - ./tests/:/master/integrational_tests/tests
      - ../dj_cqrs:/master/dj_cqrs
